package com.xworkz.Instance;

import com.xworkz.Instance.Airport.*;
import com.xworkz.Instance.Animal.*;
import com.xworkz.Instance.Bike.*;
import com.xworkz.Instance.Laptop.*;
import com.xworkz.Instance.Mall.*;

public class Runner {
    public static void main(String[] args) {
        System.out.println("=========================animal=====================================================");
        Animal animal=new Bear();
        animal.run();
        animal.play();
        animal.drink();
        animal.sleep();
        animal.scratch();
        System.out.println("======================================================================================");
         Bear bear=new Bear();
         bear.eat();
        System.out.println("======================================================================================");
        Cat cat=new Cat();
        cat.play();
        System.out.println("======================================================================================");
        Cheetah cheetah=new Cheetah();
        cheetah.sprint();
        System.out.println("======================================================================================");
        Crocodile crocodile=new Crocodile();
        crocodile.swim();
        System.out.println("======================================================================================");
        Deer deer=new Deer();
        deer.lookAround();
        System.out.println("======================================================================================");
        Dog dog=new Dog();
        dog.wagTail();
        System.out.println("======================================================================================");
        Dolphin dolphin=new Dolphin();
        dolphin.jump();
        System.out.println("======================================================================================");
        Eagle eagle=new Eagle();
        eagle.soar();
        System.out.println("======================================================================================");
        Elephant elephant=new Elephant();
        elephant.trumpet();
        System.out.println("======================================================================================");
        Fox fox=new Fox();
        fox.sneak();
        System.out.println("======================================================================================");
        Giraffe giraffe=new Giraffe();
        giraffe.eatLeaves();
        System.out.println("======================================================================================");
        Gorilla gorilla=new Gorilla();
        gorilla.poundChest();
        System.out.println("======================================================================================");
        Hippopotamus hippopotamus=new Hippopotamus();
        hippopotamus.submerge();
        System.out.println("======================================================================================");
        Kangaroo kangaroo=new Kangaroo();
        kangaroo.carryJoey();
        System.out.println("======================================================================================");
        Lion lion=new Lion();
        lion.roar();
        System.out.println("======================================================================================");
        Monkey monkey=new Monkey();
        monkey.climb();
        System.out.println("======================================================================================");
        Owl owl=new Owl();
        owl.hoot();
        System.out.println("======================================================================================");
        Penguin penguin=new Penguin();
        penguin.waddle();
        System.out.println("======================================================================================");
        Snake snake=new Snake();
        snake.slither();
        System.out.println("======================================================================================");
        Tiger tiger=new Tiger();
        tiger.hunt();
        System.out.println("======================================================================================");
        Wolf wolf=new Wolf();
        wolf.huntInPack();
        System.out.println("======================================================================================");
        Zebra zebra=new Zebra();
        zebra.graze();
        System.out.println("=======================================laptop===============================================");

        Lap lap=new Acer();
        lap.charge();
        lap.powerOn();
        lap.powerOff();
        lap.restart();
        lap.sleep();
        System.out.println("======================================================================================");
        Acer acer=new Acer();
        acer.features();
        System.out.println("======================================================================================");
        Alienware alienware=new Alienware();
        alienware.features();
        System.out.println("======================================================================================");
        Aorus aorus=new Aorus();
        aorus.features();
        System.out.println("======================================================================================");
        Apple apple=new Apple();
        apple.features();
        System.out.println("======================================================================================");
        Asus asus=new Asus();
        asus.features();
        System.out.println("======================================================================================");
        Dell dell=new Dell();
        dell.features();
        System.out.println("======================================================================================");
        EVGA evga=new EVGA();
        evga.features();
        System.out.println("======================================================================================");
        Fujitsu fujitsu=new Fujitsu();
        fujitsu.features();
        System.out.println("======================================================================================");
        HP hp=new HP();
        hp.features();
        System.out.println("======================================================================================");
        Huawei huawei=new Huawei();
        huawei.features();
        System.out.println("======================================================================================");
        Legion legion=new Legion();
        legion.features();
        System.out.println("======================================================================================");
        LG lg=new LG();
        lg.features();
        System.out.println("======================================================================================");
        Microsoft microsoft=new Microsoft();
        microsoft.features();
        System.out.println("======================================================================================");
        MSI msi=new MSI();
        msi.features();
        System.out.println("======================================================================================");
        Lenovo lenovo=new Lenovo();
        lenovo.features();
        System.out.println("======================================================================================");
        MSIGaming msiGaming=new MSIGaming();
        msiGaming.features();
        System.out.println("======================================================================================");
        Omen omen=new Omen();
        omen.features();
        System.out.println("======================================================================================");
        Panasonic panasonic=new Panasonic();
        panasonic.features();
        System.out.println("======================================================================================");
        Razer razer=new Razer();
        razer.features();
        System.out.println("======================================================================================");
        RazerBlade razerBlade=new RazerBlade();
        razerBlade.features();
        System.out.println("======================================================================================");
        ROG rog=new ROG();
        rog.features();
        System.out.println("======================================================================================");
        Samsung samsung=new Samsung();
        samsung.features();
        System.out.println("======================================================================================");
        Sony sony=new Sony();
        sony.features();
        System.out.println("======================================================================================");
        Toshiba toshiba=new Toshiba();
        toshiba.features();

        System.out.println("=======================================airport=================================");
        Airport airport=new Airport();
        airport.board();
        airport.checkIn();
        airport.land();
        airport.securityCheck();
        airport.takeOff();
        System.out.println("======================================================================================");
        Chennai chennai=new Chennai();
        chennai.operate();
        System.out.println("======================================================================================");
        KempegowdaInternational kempegowdaInternational=new KempegowdaInternational();
        kempegowdaInternational.operate();
        System.out.println("======================================================================================");
        RajivGandhi rajivGandhi=new RajivGandhi();
        rajivGandhi.operate();
        System.out.println("======================================================================================");
        ShivajiMaharaj shivajiMaharaj=new ShivajiMaharaj();
        shivajiMaharaj.operate();
        System.out.println("==============================Bike========================================================");
        Bikes bikes=new Aprilia();
        bikes.accelerate();
        bikes.brake();
        bikes.honk();
        bikes.start();
        bikes.stop();
        System.out.println("======================================================================================");
        Aprilia aprilia=new Aprilia();
        aprilia.ride();
        System.out.println("======================================================================================");
        Bajaj bajaj=new Bajaj();
        bajaj.ride();
        System.out.println("======================================================================================");
        Benelli benelli=new Benelli();
        benelli.ride();
        System.out.println("======================================================================================");
        BMW bmw=new BMW();
        bmw.ride();
        System.out.println("======================================================================================");
        CFMoto cfMoto=new CFMoto();
        cfMoto.ride();
        System.out.println("======================================================================================");
        Ducati ducati=new Ducati();
        ducati.ride();
        System.out.println("======================================================================================");
        GasGas gasGas=new GasGas();
        gasGas.ride();
        System.out.println("======================================================================================");
        HarleyDavidson harleyDavidson=new HarleyDavidson();
        harleyDavidson.ride();
        System.out.println("======================================================================================");
        Hero hero=new Hero();
        hero.ride();
        System.out.println("======================================================================================");
        HeroHonda heroHonda=new HeroHonda();
        heroHonda.ride();
        System.out.println("======================================================================================");
        Husqvarna husqvarna=new Husqvarna();
        husqvarna.ride();
        System.out.println("======================================================================================");
        Indian indian=new Indian();
        indian.ride();
        System.out.println("======================================================================================");
        Kawasaki kawasaki=new Kawasaki();
        kawasaki.ride();
        System.out.println("======================================================================================");
        KTM ktm=new KTM();
        ktm.ride();
        System.out.println("======================================================================================");
        MotoGuzzi motoGuzzi=new MotoGuzzi();
        motoGuzzi.ride();
        System.out.println("======================================================================================");
        MVAgusta mvAgusta=new MVAgusta();
        mvAgusta.ride();
        System.out.println("======================================================================================");
        RoyalEnfield royalEnfield=new RoyalEnfield();
        royalEnfield.ride();
        System.out.println("======================================================================================");
        Suzuki suzuki=new Suzuki();
        suzuki.ride();
        System.out.println("======================================================================================");
        Triumph triumph=new Triumph();
        triumph.ride();
        System.out.println("======================================================================================");
        TVS tvs=new TVS();
        tvs.ride();
        System.out.println("======================================================================================");
        Vespa vespa=new Vespa();
        vespa.ride();
        System.out.println("======================================================================================");
        Yamaha yamaha=new Yamaha();
        yamaha.ride();
        System.out.println("=======================================mall===============================================");
        Mall mall=new Mall();
        mall.close();
        mall.eat();
        mall.entertain();
        mall.open();
        mall.shop();
        System.out.println("======================================================================================");
        AmbienceMall ambienceMall=new AmbienceMall();
        ambienceMall.visit();
        System.out.println("======================================================================================");
        CityCentreMall cityCentreMall=new CityCentreMall();
        cityCentreMall.visit();
        System.out.println("======================================================================================");
        DLFPromenade dlfPromenade=new DLFPromenade();
        dlfPromenade.visit();
        System.out.println("======================================================================================");
        ElanteMall elanteMall=new ElanteMall();
        elanteMall.visit();
        System.out.println("======================================================================================");
        ExpressAvenue expressAvenue=new ExpressAvenue();
        expressAvenue.visit();
        System.out.println("======================================================================================");
        ForumMall forumMall=new ForumMall();
        forumMall.visit();
        System.out.println("======================================================================================");
        GIPMall gipMall=new GIPMall();
        gipMall.visit();
        System.out.println("======================================================================================");
        InfinityMall infinityMall=new InfinityMall();
        infinityMall.visit();
        System.out.println("======================================================================================");
        InorbitMall inorbitMall=new InorbitMall();
        inorbitMall.visit();
        System.out.println("======================================================================================");
        LuLuMall luLuMall=new LuLuMall();
        luLuMall.visit();
        System.out.println("======================================================================================");
        MagnetoMall magnetoMall=new MagnetoMall();
        magnetoMall.visit();
        System.out.println("======================================================================================");
        MantriSquare mantriSquare=new MantriSquare();
        mantriSquare.visit();
        System.out.println("======================================================================================");
        OberoiMall oberoiMall=new OberoiMall();
        oberoiMall.visit();
        System.out.println("======================================================================================");
        OrionMall orionMall=new OrionMall();
        orionMall.visit();
        System.out.println("======================================================================================");
        PalladiumMall palladiumMall=new PalladiumMall();
        palladiumMall.visit();
        System.out.println("======================================================================================");
        Phoenix phoenix=new Phoenix();
        phoenix.visit();
        System.out.println("======================================================================================");
        ProzoneMall prozoneMall=new ProzoneMall();
        prozoneMall.visit();
        System.out.println("======================================================================================");
        RCityMall rCityMall=new RCityMall();
        rCityMall.visit();
        System.out.println("======================================================================================");
        SelectCityWalk selectCityWalk=new SelectCityWalk();
        selectCityWalk.visit();
        System.out.println("======================================================================================");
        SouthCityMall southCityMall=new SouthCityMall();
        southCityMall.visit();
        System.out.println("======================================================================================");
        VivianaMall vivianaMall=new VivianaMall();
        vivianaMall.visit();
        System.out.println("======================================================================================");

    }

}
