package com.xworkz.Instance;

import com.xworkz.Instance.Airport.*;
import com.xworkz.Instance.Animal.*;
import com.xworkz.Instance.Bike.*;
import com.xworkz.Instance.Laptop.*;
import com.xworkz.Instance.Mall.*;

import javax.crypto.Mac;

public class Runner {
    public static void main(String[] args) {
        System.out.println("===========================animal=====================================================");
        Animal animal=new Bear();
        animal.run();
        animal.play();
        animal.drink();
        animal.sleep();
        animal.scratch();
        System.out.println("======================================================================================");
         Bear bear=new Bear();
         bear.eat();
         bear.run();
         bear.play();
         bear.drink();
         bear.sleep();
         bear.scratch();
        System.out.println("======================================================================================");
        Cat cat=new Cat();
        cat.play();
        cat.run();
        cat.play();
        cat.drink();
        cat.sleep();
        cat.scratch();
        System.out.println("======================================================================================");
        Cheetah cheetah=new Cheetah();
        cheetah.sprint();
        cheetah.run();
        cheetah.play();
        cheetah.drink();
        cheetah.sleep();
        cheetah.scratch();
        System.out.println("======================================================================================");
        Crocodile crocodile=new Crocodile();
        crocodile.swim();
        crocodile.run();
        crocodile.play();
        crocodile.drink();
        crocodile.sleep();
        crocodile.scratch();
        System.out.println("======================================================================================");
        Deer deer=new Deer();
        deer.lookAround();
        deer.run();
        deer.play();
        deer.drink();
        deer.sleep();
        deer.scratch();
        System.out.println("======================================================================================");
        Dog dog=new Dog();
        dog.wagTail();
        dog.run();
        dog.play();
        dog.drink();
        dog.sleep();
        dog.scratch();
        System.out.println("======================================================================================");
        Dolphin dolphin=new Dolphin();
        dolphin.jump();
        dolphin.run();
        dolphin.play();
        dolphin.drink();
        dolphin.sleep();
        dolphin.scratch();
        System.out.println("======================================================================================");
        Eagle eagle=new Eagle();
        eagle.soar();
        eagle.run();
        eagle.play();
        eagle.drink();
        eagle.sleep();
        eagle.scratch();
        System.out.println("======================================================================================");
        Elephant elephant=new Elephant();
        elephant.trumpet();
        elephant.run();
        elephant.play();
        elephant.drink();
        elephant.sleep();
        elephant.scratch();
        System.out.println("======================================================================================");
        Fox fox=new Fox();
        fox.sneak();
        fox.run();
        fox.play();
        fox.drink();
        fox.sleep();
        fox.scratch();
        System.out.println("======================================================================================");
        Giraffe giraffe=new Giraffe();
        giraffe.eatLeaves();
        giraffe.run();
        giraffe.play();
        giraffe.drink();
        giraffe.sleep();
        giraffe.scratch();
        System.out.println("======================================================================================");
        Gorilla gorilla=new Gorilla();
        gorilla.poundChest();
        gorilla.run();
        gorilla.play();
        gorilla.drink();
        gorilla.sleep();
        gorilla.scratch();
        System.out.println("======================================================================================");
        Hippopotamus hippopotamus=new Hippopotamus();
        hippopotamus.submerge();
        hippopotamus.run();
        hippopotamus.play();
        hippopotamus.drink();
        hippopotamus.sleep();
        hippopotamus.scratch();
        System.out.println("======================================================================================");
        Kangaroo kangaroo=new Kangaroo();
        kangaroo.carryJoey();
        kangaroo.run();
        kangaroo.play();
        kangaroo.drink();
        kangaroo.sleep();
        kangaroo.scratch();
        System.out.println("======================================================================================");
        Lion lion=new Lion();
        lion.roar();
        lion.run();
        lion.play();
        lion.drink();
        lion.sleep();
        lion.scratch();
        System.out.println("======================================================================================");
        Monkey monkey=new Monkey();
        monkey.climb();
        monkey.run();
        monkey.play();
        monkey.drink();
        monkey.sleep();
        monkey.scratch();
        System.out.println("======================================================================================");
        Owl owl=new Owl();
        owl.hoot();
        owl.run();
        owl.play();
        owl.drink();
        owl.sleep();
        owl.scratch();
        System.out.println("======================================================================================");
        Penguin penguin=new Penguin();
        penguin.waddle();
        penguin.run();
        penguin.play();
        penguin.drink();
        penguin.sleep();
        penguin.scratch();
        System.out.println("======================================================================================");
        Snake snake=new Snake();
        snake.slither();
        snake.run();
        snake.play();
        snake.drink();
        snake.sleep();
        snake.scratch();
        System.out.println("======================================================================================");
        Tiger tiger=new Tiger();
        tiger.hunt();
        tiger.run();
        tiger.play();
        tiger.drink();
        tiger.sleep();
        tiger.scratch();
        System.out.println("======================================================================================");
        Wolf wolf=new Wolf();
        wolf.huntInPack();
        wolf.run();
        wolf.play();
        wolf.drink();
        wolf.sleep();
        wolf.scratch();
        System.out.println("======================================================================================");
        Zebra zebra=new Zebra();
        zebra.graze();
        zebra.run();
        zebra.play();
        zebra.drink();
        zebra.sleep();
        zebra.scratch();
        System.out.println("=======================================laptop===============================================");

        Lap lap=new Acer();
        lap.charge();
        lap.powerOn();
        lap.powerOff();
        lap.restart();
        lap.sleep();
        System.out.println("======================================================================================");
        Acer acer=new Acer();
        acer.features();
        acer.charge();
        acer.powerOn();
        acer.powerOff();
        acer.restart();
        acer.sleep();
        System.out.println("======================================================================================");
        Alienware alienware=new Alienware();
        alienware.features();
        alienware.charge();
        alienware.powerOn();
        alienware.powerOff();
        alienware.restart();
        alienware.sleep();
        System.out.println("======================================================================================");
        Aorus aorus=new Aorus();
        aorus.features();
        aorus.charge();
        aorus.powerOn();
        aorus.powerOff();
        aorus.restart();
        aorus.sleep();
        System.out.println("======================================================================================");
        Apple apple=new Apple();
        apple.features();
        apple.charge();
        apple.powerOn();
        apple.powerOff();
        apple.restart();
        apple.sleep();
        System.out.println("======================================================================================");
        Asus asus=new Asus();
        asus.features();
        asus.charge();
        asus.powerOn();
        asus.powerOff();
        asus.restart();
        asus.sleep();
        System.out.println("======================================================================================");
        Dell dell=new Dell();
        dell.features();
        dell.charge();
        dell.powerOn();
        dell.powerOff();
        dell.restart();
        dell.sleep();
        System.out.println("======================================================================================");
        EVGA evga=new EVGA();
        evga.features();
        evga.charge();
        evga.powerOn();
        evga.powerOff();
        evga.restart();
        evga.sleep();
        System.out.println("======================================================================================");
        Fujitsu fujitsu=new Fujitsu();
        fujitsu.features();
        fujitsu.charge();
        fujitsu.powerOn();
        fujitsu.powerOff();
        fujitsu.restart();
        fujitsu.sleep();
        System.out.println("======================================================================================");
        HP hp=new HP();
        hp.features();
        hp.charge();
        hp.powerOn();
        hp.powerOff();
        hp.restart();
        hp.sleep();
        System.out.println("======================================================================================");
        Huawei huawei=new Huawei();
        huawei.features();
        huawei.charge();
        huawei.powerOn();
        huawei.powerOff();
        huawei.restart();
        huawei.sleep();
        System.out.println("======================================================================================");
        Legion legion=new Legion();
        legion.features();
        legion.charge();
        legion.powerOn();
        legion.powerOff();
        legion.restart();
        legion.sleep();
        System.out.println("======================================================================================");
        LG lg=new LG();
        lg.features();
        lg.charge();
        lg.powerOn();
        lg.powerOff();
        lg.restart();
        lg.sleep();
        System.out.println("======================================================================================");
        Microsoft microsoft=new Microsoft();
        microsoft.features();
        microsoft.charge();
        microsoft.powerOn();
        microsoft.powerOff();
        microsoft.restart();
        microsoft.sleep();
        System.out.println("======================================================================================");
        MSI msi=new MSI();
        msi.features();
        msi.charge();
        msi.powerOn();
        msi.powerOff();
        msi.restart();
        msi.sleep();
        System.out.println("======================================================================================");
        Lenovo lenovo=new Lenovo();
        lenovo.features();
        lenovo.charge();
        lenovo.powerOn();
        lenovo.powerOff();
        lenovo.restart();
        lenovo.sleep();
        System.out.println("======================================================================================");
        MSIGaming msiGaming=new MSIGaming();
        msiGaming.features();
        msiGaming.charge();
        msiGaming.powerOn();
        msiGaming.powerOff();
        msiGaming.restart();
        msiGaming.sleep();
        System.out.println("======================================================================================");
        Omen omen=new Omen();
        omen.features();
        omen.charge();
        omen.powerOn();
        omen.powerOff();
        omen.restart();
        omen.sleep();
        System.out.println("======================================================================================");
        Panasonic panasonic=new Panasonic();
        panasonic.features();
        panasonic.charge();
        panasonic.powerOn();
        panasonic.powerOff();
        panasonic.restart();
        panasonic.sleep();
        System.out.println("======================================================================================");
        Razer razer=new Razer();
        razer.features();
        razer.charge();
        razer.powerOn();
        razer.powerOff();
        razer.restart();
        razer.sleep();
        System.out.println("======================================================================================");
        RazerBlade razerBlade=new RazerBlade();
        razerBlade.features();
        razerBlade.charge();
        razerBlade.powerOn();
        razerBlade.powerOff();
        razerBlade.restart();
        razerBlade.sleep();
        System.out.println("======================================================================================");
        ROG rog=new ROG();
        rog.features();
        rog.charge();
        rog.powerOn();
        rog.powerOff();
        rog.restart();
        rog.sleep();
        System.out.println("======================================================================================");
        Samsung samsung=new Samsung();
        samsung.features();
        samsung.charge();
        samsung.powerOn();
        samsung.powerOff();
        samsung.restart();
        samsung.sleep();
        System.out.println("======================================================================================");
        Sony sony=new Sony();
        sony.features();
        sony.charge();
        sony.powerOn();
        sony.powerOff();
        sony.restart();
        sony.sleep();
        System.out.println("======================================================================================");
        Toshiba toshiba=new Toshiba();
        toshiba.features();
        toshiba.charge();
        toshiba.powerOn();
        toshiba.powerOff();
        toshiba.restart();
        toshiba.sleep();
        System.out.println("=======================================airport=================================");
        Airport airport=new Chennai();
        airport.board();
        airport.checkIn();
        airport.land();
        airport.securityCheck();
        airport.takeOff();
        System.out.println("======================================================================================");
        Chennai chennai=new Chennai();
        chennai.operate();
        chennai.land();
        chennai.board();
        chennai.checkIn();
        chennai.takeOff();
        chennai.securityCheck();
        System.out.println("======================================================================================");
        KempegowdaInternational kempegowdaInternational=new KempegowdaInternational();
        kempegowdaInternational.operate();
        kempegowdaInternational.board();
        kempegowdaInternational.checkIn();
        kempegowdaInternational.land();
        kempegowdaInternational.securityCheck();
        kempegowdaInternational.takeOff();
        System.out.println("======================================================================================");
        RajivGandhi rajivGandhi=new RajivGandhi();
        rajivGandhi.operate();
        rajivGandhi.operate();
        rajivGandhi.board();
        rajivGandhi.checkIn();
        rajivGandhi.land();
        rajivGandhi.securityCheck();
        rajivGandhi.takeOff();
        System.out.println("======================================================================================");
        ShivajiMaharaj shivajiMaharaj=new ShivajiMaharaj();
        shivajiMaharaj.operate();
        shivajiMaharaj.operate();
        shivajiMaharaj.board();
        shivajiMaharaj.checkIn();
        shivajiMaharaj.land();
        shivajiMaharaj.securityCheck();
        shivajiMaharaj.takeOff();
        System.out.println("==============================Bike========================================================");
        Bikes bikes=new Aprilia();
        bikes.accelerate();
        bikes.brake();
        bikes.honk();
        bikes.start();
        bikes.stop();
        System.out.println("======================================================================================");
        Aprilia aprilia=new Aprilia();
        aprilia.ride();
        aprilia.accelerate();
        aprilia.brake();
        aprilia.honk();
        aprilia.start();
        aprilia.stop();
        System.out.println("======================================================================================");
        Bajaj bajaj=new Bajaj();
        bajaj.ride();
        bajaj.accelerate();
        bajaj.brake();
        bajaj.honk();
        bajaj.start();
        bajaj.stop();
        System.out.println("======================================================================================");
        Benelli benelli=new Benelli();
        benelli.ride();
        benelli.accelerate();
        benelli.brake();
        benelli.honk();
        benelli.start();
        benelli.stop();
        System.out.println("======================================================================================");
        BMW bmw=new BMW();
        bmw.ride();
        bmw.accelerate();
        bmw.brake();
        bmw.honk();
        bmw.start();
        bmw.stop();
        System.out.println("======================================================================================");
        CFMoto cfMoto=new CFMoto();
        cfMoto.ride();
        cfMoto.accelerate();
        cfMoto.brake();
        cfMoto.honk();
        cfMoto.start();
        cfMoto.stop();
        System.out.println("======================================================================================");
        Ducati ducati=new Ducati();
        ducati.ride();
        ducati.accelerate();
        ducati.brake();
        ducati.honk();
        ducati.start();
        ducati.stop();
        System.out.println("======================================================================================");
        GasGas gasGas=new GasGas();
        gasGas.ride();
        gasGas.accelerate();
        gasGas.brake();
        gasGas.honk();
        gasGas.start();
        gasGas.stop();
        System.out.println("======================================================================================");
        HarleyDavidson harleyDavidson=new HarleyDavidson();
        harleyDavidson.ride();
        harleyDavidson.accelerate();
        harleyDavidson.brake();
        harleyDavidson.honk();
        harleyDavidson.start();
        harleyDavidson.stop();
        System.out.println("======================================================================================");
        Hero hero=new Hero();
        hero.ride();
        hero.accelerate();
        hero.brake();
        hero.honk();
        hero.start();
        hero.stop();
        System.out.println("======================================================================================");
        HeroHonda heroHonda=new HeroHonda();
        heroHonda.ride();
        heroHonda.accelerate();
        heroHonda.brake();
        heroHonda.honk();
        heroHonda.start();
        heroHonda.stop();
        System.out.println("======================================================================================");
        Husqvarna husqvarna=new Husqvarna();
        husqvarna.ride();
        husqvarna.accelerate();
        husqvarna.brake();
        husqvarna.honk();
        husqvarna.start();
        husqvarna.stop();
        System.out.println("======================================================================================");
        Indian indian=new Indian();
        indian.ride();
        indian.accelerate();
        indian.brake();
        indian.honk();
        indian.start();
        indian.stop();
        System.out.println("======================================================================================");
        Kawasaki kawasaki=new Kawasaki();
        kawasaki.ride();
        kawasaki.accelerate();
        kawasaki.brake();
        kawasaki.honk();
        kawasaki.start();
        kawasaki.stop();
        System.out.println("======================================================================================");
        KTM ktm=new KTM();
        ktm.ride();
        ktm.accelerate();
        ktm.brake();
        ktm.honk();
        ktm.start();
        ktm.stop();
        System.out.println("======================================================================================");
        MotoGuzzi motoGuzzi=new MotoGuzzi();
        motoGuzzi.ride();
        motoGuzzi.accelerate();
        motoGuzzi.brake();
        motoGuzzi.honk();
        motoGuzzi.start();
        motoGuzzi.stop();
        System.out.println("======================================================================================");
        MVAgusta mvAgusta=new MVAgusta();
        mvAgusta.ride();
        mvAgusta.accelerate();
        mvAgusta.brake();
        mvAgusta.honk();
        mvAgusta.start();
        mvAgusta.stop();
        System.out.println("======================================================================================");
        RoyalEnfield royalEnfield=new RoyalEnfield();
        royalEnfield.ride();
        royalEnfield.accelerate();
        royalEnfield.brake();
        royalEnfield.honk();
        royalEnfield.start();
        royalEnfield.stop();
        System.out.println("======================================================================================");
        Suzuki suzuki=new Suzuki();
        suzuki.ride();
        suzuki.accelerate();
        suzuki.brake();
        suzuki.honk();
        suzuki.start();
        suzuki.stop();
        System.out.println("======================================================================================");
        Triumph triumph=new Triumph();
        triumph.ride();
        triumph.accelerate();
        triumph.brake();
        triumph.honk();
        triumph.start();
        triumph.stop();
        System.out.println("======================================================================================");
        TVS tvs=new TVS();
        tvs.ride();
        tvs.accelerate();
        tvs.brake();
        tvs.honk();
        tvs.start();
        tvs.stop();
        System.out.println("======================================================================================");
        Vespa vespa=new Vespa();
        vespa.ride();
        vespa.accelerate();
        vespa.brake();
        vespa.honk();
        vespa.start();
        vespa.stop();
        System.out.println("======================================================================================");
        Yamaha yamaha=new Yamaha();
        yamaha.ride();
        yamaha.accelerate();
        yamaha.brake();
        yamaha.honk();
        yamaha.start();
        yamaha.stop();
        System.out.println("=======================================mall===============================================");
        Mall mall=new AmbienceMall();
        mall.close();
        mall.eat();
        mall.entertain();
        mall.open();
        mall.shop();
        System.out.println("======================================================================================");
        AmbienceMall ambienceMall=new AmbienceMall();
        ambienceMall.visit();
        ambienceMall.close();
        ambienceMall.eat();
        ambienceMall.entertain();
        ambienceMall.open();
        ambienceMall.shop();
        System.out.println("======================================================================================");
        CityCentreMall cityCentreMall=new CityCentreMall();
        cityCentreMall.visit();
        cityCentreMall.close();
        cityCentreMall.eat();
        cityCentreMall.entertain();
        cityCentreMall.open();
        cityCentreMall.shop();
        System.out.println("======================================================================================");
        DLFPromenade dlfPromenade=new DLFPromenade();
        dlfPromenade.visit();
        dlfPromenade.close();
        dlfPromenade.eat();
        dlfPromenade.entertain();
        dlfPromenade.open();
        dlfPromenade.shop();
        System.out.println("======================================================================================");
        ElanteMall elanteMall=new ElanteMall();
        elanteMall.visit();
        elanteMall.close();
        elanteMall.eat();
        elanteMall.entertain();
        elanteMall.open();
        elanteMall.shop();
        System.out.println("======================================================================================");
        ExpressAvenue expressAvenue=new ExpressAvenue();
        expressAvenue.visit();
        expressAvenue.close();
        expressAvenue.eat();
        expressAvenue.entertain();
        expressAvenue.open();
        expressAvenue.shop();
        System.out.println("======================================================================================");
        ForumMall forumMall=new ForumMall();
        forumMall.visit();
        forumMall.close();
        forumMall.eat();
        forumMall.entertain();
        forumMall.open();
        forumMall.shop();
        System.out.println("======================================================================================");
        GIPMall gipMall=new GIPMall();
        gipMall.visit();
        gipMall.close();
        gipMall.eat();
        gipMall.entertain();
        gipMall.open();
        gipMall.shop();
        System.out.println("======================================================================================");
        InfinityMall infinityMall=new InfinityMall();
        infinityMall.visit();
        infinityMall.close();
        infinityMall.eat();
        infinityMall.entertain();
        infinityMall.open();
        infinityMall.shop();
        System.out.println("======================================================================================");
        InorbitMall inorbitMall=new InorbitMall();
        inorbitMall.visit();
        inorbitMall.close();
        inorbitMall.eat();
        inorbitMall.entertain();
        inorbitMall.open();
        inorbitMall.shop();
        System.out.println("======================================================================================");
        LuLuMall luLuMall=new LuLuMall();
        luLuMall.visit();
        luLuMall.close();
        luLuMall.eat();
        luLuMall.entertain();
        luLuMall.open();
        luLuMall.shop();
        System.out.println("======================================================================================");
        MagnetoMall magnetoMall=new MagnetoMall();
        magnetoMall.visit();
        magnetoMall.close();
        magnetoMall.eat();
        magnetoMall.entertain();
        magnetoMall.open();
        magnetoMall.shop();
        System.out.println("======================================================================================");
        MantriSquare mantriSquare=new MantriSquare();
        mantriSquare.visit();
        mantriSquare.close();
        mantriSquare.eat();
        mantriSquare.entertain();
        mantriSquare.open();
        mantriSquare.shop();
        System.out.println("======================================================================================");
        OberoiMall oberoiMall=new OberoiMall();
        oberoiMall.visit();
        oberoiMall.close();
        oberoiMall.eat();
        oberoiMall.entertain();
        oberoiMall.open();
        oberoiMall.shop();
        System.out.println("======================================================================================");
        OrionMall orionMall=new OrionMall();
        orionMall.visit();
        orionMall.close();
        orionMall.eat();
        orionMall.entertain();
        orionMall.open();
        orionMall.shop();
        System.out.println("======================================================================================");
        PalladiumMall palladiumMall=new PalladiumMall();
        palladiumMall.visit();
        palladiumMall.close();
        palladiumMall.eat();
        palladiumMall.entertain();
        palladiumMall.open();
        palladiumMall.shop();

        System.out.println("======================================================================================");
        Phoenix phoenix=new Phoenix();
        phoenix.visit();
        phoenix.close();
        phoenix.eat();
        phoenix.entertain();
        phoenix.open();
        phoenix.shop();
        System.out.println("======================================================================================");
        ProzoneMall prozoneMall=new ProzoneMall();
        prozoneMall.visit();
        prozoneMall.close();
        prozoneMall.eat();
        prozoneMall.entertain();
        prozoneMall.open();
        prozoneMall.shop();
        System.out.println("======================================================================================");
        RCityMall rCityMall=new RCityMall();
        rCityMall.visit();
        rCityMall.close();
        rCityMall.eat();
        rCityMall.entertain();
        rCityMall.open();
        rCityMall.shop();
        System.out.println("======================================================================================");
        SelectCityWalk selectCityWalk=new SelectCityWalk();
        selectCityWalk.visit();
        selectCityWalk.close();
        selectCityWalk.eat();
        selectCityWalk.entertain();
        selectCityWalk.open();
        selectCityWalk.shop();
        System.out.println("======================================================================================");
        SouthCityMall southCityMall=new SouthCityMall();
        southCityMall.visit();
        southCityMall.close();
        southCityMall.eat();
        southCityMall.entertain();
        southCityMall.open();
        southCityMall.shop();
        System.out.println("======================================================================================");
        VivianaMall vivianaMall=new VivianaMall();
        vivianaMall.visit();
        vivianaMall.close();
        vivianaMall.eat();
        vivianaMall.entertain();
        vivianaMall.open();
        vivianaMall.shop();
        System.out.println("======================================================================================");
        Banglore blg = new Banglore();
        blg.boarding();
        blg.ticket(blg);
        System.out.println("================================================================================");
        InternationalFlights IF=new InternationalFlights();
        IF.verifyPassport();
        IF.Arrival(IF);
        System.out.println("================================================================================");
        InternationalTerminal internationalTerminal=new InternationalTerminal();
        internationalTerminal.announceFlight();
        internationalTerminal.handleDeparture(internationalTerminal);
        System.out.println("================================================================================");
        MarinaBeach marinaBeach=new MarinaBeach();
        marinaBeach.boarding();
        marinaBeach.pricing(marinaBeach);
        System.out.println("================================================================================");
        Alligators alligators=new Alligators();
        alligators.Breath();
        alligators.swims(alligators);
        System.out.println("================================================================================");
        Baboons baboons=new Baboons();
        baboons.climb();
        baboons.chatter(baboons);
        System.out.println("================================================================================");
        Canidae canidae=new Canidae();
        canidae.hunting();
        canidae.walking(canidae);
        System.out.println("================================================================================");
        Colubridae colubridae=new Colubridae();
        colubridae.crawl();
        colubridae.hunt(colubridae);
        System.out.println("================================================================================");
        Dingo dingo=new Dingo();
        dingo.makessounds();
        dingo.sniffTrail(dingo);
        System.out.println("================================================================================");
        GaintPanda gaintPanda=new GaintPanda();
        gaintPanda.sleep();
        gaintPanda.eating(gaintPanda);
        System.out.println("================================================================================");
        GentooPenguin gentooPenguin=new GentooPenguin();
        gentooPenguin.slide();
        gentooPenguin.Jump(gentooPenguin);
        System.out.println("================================================================================");
        HarpyEagle harpyEagle=new HarpyEagle();
        harpyEagle.swoopDown();
        harpyEagle.hunt(harpyEagle);
        System.out.println("================================================================================");
        Jaguar jaguar = new Jaguar();
        jaguar.eating();
        jaguar.hunt(jaguar);
        System.out.println("================================================================================");
        Leopard leopard=new Leopard();
        leopard.hunt();
        leopard.drinking(leopard);
        System.out.println("================================================================================");
        Mammoth mammoth=new Mammoth();
        mammoth.trumpetSound();
        mammoth.roamIceAge(mammoth);
        System.out.println("================================================================================");
        Okapi okapi=new Okapi();
        okapi.nibblePlants();
        okapi.exploreForest(okapi);
        System.out.println("================================================================================");
        RedFox redFox=new RedFox();
        redFox.hide();
        redFox.exploreWoods(redFox);
        System.out.println("================================================================================");
        Reindeer reindeer=new Reindeer();
        reindeer.drinking();
        reindeer.walk(reindeer);
        System.out.println("================================================================================");
        SnowyOwl snowyOwl=new SnowyOwl();
        snowyOwl.glide();
        snowyOwl.hunt(snowyOwl);
        System.out.println("================================================================================");
        TreeKangaroo treeKangaroo=new TreeKangaroo();
        treeKangaroo.restOnTree();
        treeKangaroo.hopAround(treeKangaroo);
        System.out.println("================================================================================");
        Whale whale=new Whale();
        whale.sounds();
        whale.diveDeep(whale);
        System.out.println("================================================================================");
        ApriliaRS660 apriliaRS660=new ApriliaRS660();
        apriliaRS660.SportMode();
        apriliaRS660.prepareRide(apriliaRS660);
        System.out.println("================================================================================");
        BajajPulsar bajajPulsar=new BajajPulsar();
        bajajPulsar.boostPerformance();
        bajajPulsar.beginJourney(bajajPulsar);
        System.out.println("================================================================================");
        BenelliImperiale benelliImperiale=new BenelliImperiale();
        benelliImperiale.ClassicMode();
        benelliImperiale.initiateCruise(benelliImperiale);
        System.out.println("================================================================================");

        BMWR1250GS bmwr1250GS=new BMWR1250GS();
        bmwr1250GS.Speed();
        bmwr1250GS.startAdventure(bmwr1250GS);
        System.out.println("================================================================================");

        CFMoto650MT cfMoto650MT=new CFMoto650MT();
        cfMoto650MT.EcoBoost();
        cfMoto650MT.launchTouringMode(cfMoto650MT);
        System.out.println("================================================================================");
        DucatiPanigaleV4 ducatiPanigaleV4=new DucatiPanigaleV4();
        ducatiPanigaleV4.activateQuickShift();
        ducatiPanigaleV4.initiateRaceMode(ducatiPanigaleV4);
        System.out.println("================================================================================");

        HarleyIron883 harleyIron883=new HarleyIron883();
        harleyIron883.ThunderMode();
        harleyIron883.cruiseHighway(harleyIron883);
        System.out.println("================================================================================");

        HeroXpulse200 heroXpulse200=new HeroXpulse200();
        heroXpulse200.performance();
        heroXpulse200.beginTrailRide(heroXpulse200);
        System.out.println("================================================================================");

        HusqvarnaSvartpilen husqvarnaSvartpilen=new HusqvarnaSvartpilen();
        husqvarnaSvartpilen.Ride();
        husqvarnaSvartpilen.startUrbanScramble(husqvarnaSvartpilen);
        System.out.println("================================================================================");

        KawasakiNinja kawasakiNinja=new KawasakiNinja();
        kawasakiNinja.Control();
        kawasakiNinja.initiateTrackMode(kawasakiNinja);
        System.out.println("================================================================================");

        KTMRc390 ktmRc390=new KTMRc390();
        ktmRc390.launch();
        ktmRc390.engageRaceMode(ktmRc390);
        System.out.println("================================================================================");

        MotoGuzziV7 motoGuzziV7=new MotoGuzziV7();
        motoGuzziV7.speed();
        motoGuzziV7.beginClassicRide(motoGuzziV7);
        System.out.println("================================================================================");

        RoyalEnfieldClassic royalEnfieldClassic=new RoyalEnfieldClassic();
        royalEnfieldClassic.thump();
        royalEnfieldClassic.startVintageCruise(royalEnfieldClassic);
        System.out.println("================================================================================");

        SuzukiGixxer suzukiGixxer=new SuzukiGixxer();
        suzukiGixxer.Engine();
        suzukiGixxer.beginStreetRide(suzukiGixxer);
        System.out.println("================================================================================");
        TVSApacheRTR tvsApacheRTR=new TVSApacheRTR();
        tvsApacheRTR.Power();
        tvsApacheRTR.startCityRace(tvsApacheRTR);
        System.out.println("================================================================================");
        VespaSXL vespaSXL=new VespaSXL();
        vespaSXL.ringBell();
        vespaSXL.beginScooterCruise(vespaSXL);

        System.out.println("================================================================================");
        YamahaR15 yamahaR15=new YamahaR15();
        yamahaR15.Boost();
        yamahaR15.launchSportMode(yamahaR15);
        System.out.println("================================================================================");

        AcerNitro5 acerNitro5=new AcerNitro5();
        acerNitro5.Gaming();
        acerNitro5.startGamingSession(acerNitro5);
        System.out.println("================================================================================");

        Aorus17X aorus17X=new Aorus17X();
        aorus17X.Keyboard();
        aorus17X.initiatePerformanceMode(aorus17X);
        System.out.println("================================================================================");
        AsusROGStrix asusROGStrix=new AsusROGStrix();
        asusROGStrix.power();
        asusROGStrix.startGamingArena(asusROGStrix);
        System.out.println("================================================================================");
        DellXPS dellXPS=new DellXPS();
        dellXPS.Display();
        dellXPS.launchProductivitySuite(dellXPS);
        System.out.println("================================================================================");
        HPSpectreX360 hpSpectreX360=new HPSpectreX360();
        hpSpectreX360.Touch();
        hpSpectreX360.startCreativeWorkflow(hpSpectreX360);
        System.out.println("================================================================================");
        LenovoLegion5Pro lenovoLegion5Pro=new LenovoLegion5Pro();
        lenovoLegion5Pro.TurboCooling();
        lenovoLegion5Pro.initiateBattleMode(lenovoLegion5Pro);
        System.out.println("================================================================================");
        LenovoThinkPad lenovoThinkPad=new LenovoThinkPad();
        lenovoThinkPad.battery();
        lenovoThinkPad.startOfficeSession(lenovoThinkPad);
        System.out.println("================================================================================");
        LGGram17 lgGram17=new LGGram17();
        lgGram17.BatterySaver();
        lgGram17.startWorkSession(lgGram17);
        System.out.println("================================================================================");
        MacBookPro macc =new MacBookPro();
        macc.ProMotion();
        macc.launchCreativeSuite(macc);
        System.out.println("================================================================================");
        SamsungGalaxyBook3 samsungGalaxyBook3=new SamsungGalaxyBook3();
        samsungGalaxyBook3.speed();
        samsungGalaxyBook3.startSmartSync(samsungGalaxyBook3);
        System.out.println("================================================================================");
        SonyVaioZ sonyVaioZ=new SonyVaioZ();
        sonyVaioZ.version();
        sonyVaioZ.launchPerformanceSuite(sonyVaioZ);
        System.out.println("================================================================================");

        SurfaceLaptop5 surfaceLaptop=new SurfaceLaptop5();
        surfaceLaptop.ScreenTouch();
        surfaceLaptop.launchDesignApp(surfaceLaptop);
        System.out.println("================================================================================");






    }

}
