package com.xworkz.Instance;

import com.xworkz.Instance.Animal.*;
import com.xworkz.Instance.Laptop.*;

public class Runner {
    public static void main(String[] args) {
        Animal animal=new Bear();
        animal.run();
        animal.play();
        animal.drink();
        animal.sleep();
        animal.scratch();
        System.out.println("======================================================================================");
         Bear bear=new Bear();
         bear.eat();
        System.out.println("======================================================================================");
        Cat cat=new Cat();
        cat.play();
        System.out.println("======================================================================================");
        Cheetah cheetah=new Cheetah();
        cheetah.sprint();
        System.out.println("======================================================================================");
        Crocodile crocodile=new Crocodile();
        crocodile.swim();
        System.out.println("======================================================================================");
        Deer deer=new Deer();
        deer.lookAround();
        System.out.println("======================================================================================");
        Dog dog=new Dog();
        dog.wagTail();
        System.out.println("======================================================================================");
        Dolphin dolphin=new Dolphin();
        dolphin.jump();
        System.out.println("======================================================================================");
        Eagle eagle=new Eagle();
        eagle.soar();
        System.out.println("======================================================================================");
        Elephant elephant=new Elephant();
        elephant.trumpet();
        System.out.println("======================================================================================");
        Fox fox=new Fox();
        fox.sneak();
        System.out.println("======================================================================================");
        Giraffe giraffe=new Giraffe();
        giraffe.eatLeaves();
        System.out.println("======================================================================================");
        Gorilla gorilla=new Gorilla();
        gorilla.poundChest();
        System.out.println("======================================================================================");
        Hippopotamus hippopotamus=new Hippopotamus();
        hippopotamus.submerge();
        System.out.println("======================================================================================");
        Kangaroo kangaroo=new Kangaroo();
        kangaroo.carryJoey();
        System.out.println("======================================================================================");
        Lion lion=new Lion();
        lion.roar();
        System.out.println("======================================================================================");
        Monkey monkey=new Monkey();
        monkey.climb();
        System.out.println("======================================================================================");
        Owl owl=new Owl();
        owl.hoot();
        System.out.println("======================================================================================");
        Penguin penguin=new Penguin();
        penguin.waddle();
        System.out.println("======================================================================================");
        Snake snake=new Snake();
        snake.slither();
        System.out.println("======================================================================================");
        Tiger tiger=new Tiger();
        tiger.hunt();
        System.out.println("======================================================================================");
        Wolf wolf=new Wolf();
        wolf.huntInPack();
        System.out.println("======================================================================================");
        Zebra zebra=new Zebra();
        zebra.graze();
        System.out.println("======================================================================================");

        Lap lap=new Acer();

        lap.charge();
        lap.powerOn();
        lap.powerOff();
        lap.restart();
        lap.sleep();
        System.out.println("======================================================================================");
        Acer acer=new Acer();
        acer.features();
        System.out.println("======================================================================================");
        Alienware alienware=new Alienware();
        alienware.features();
        System.out.println("======================================================================================");
        Aorus aorus=new Aorus();
        aorus.features();
        System.out.println("======================================================================================");
        Apple apple=new Apple();
        apple.features();
        System.out.println("======================================================================================");
        Asus asus=new Asus();
        asus.features();
        System.out.println("======================================================================================");
        Dell dell=new Dell();
        dell.features();
        System.out.println("======================================================================================");
        EVGA evga=new EVGA();
        evga.features();
        System.out.println("======================================================================================");
        Fujitsu fujitsu=new Fujitsu();
        fujitsu.features();
        System.out.println("======================================================================================");
        HP hp=new HP();
        hp.features();
        System.out.println("======================================================================================");
        Huawei huawei=new Huawei();
        huawei.features();
        System.out.println("======================================================================================");
        Legion legion=new Legion();
        legion.features();
        System.out.println("======================================================================================");
        LG lg=new LG();
        lg.features();
        System.out.println("======================================================================================");
        Microsoft microsoft=new Microsoft();
        microsoft.features();
        System.out.println("======================================================================================");
        MSI msi=new MSI();
        msi.features();
        System.out.println("======================================================================================");
        Lenovo lenovo=new Lenovo();
        lenovo.features();
        System.out.println("======================================================================================");
        MSIGaming msiGaming=new MSIGaming();
        msiGaming.features();
        System.out.println("======================================================================================");
        Omen omen=new Omen();
        omen.features();
        System.out.println("======================================================================================");
        Panasonic panasonic=new Panasonic();
        panasonic.features();
        System.out.println("======================================================================================");
        Razer razer=new Razer();
        razer.features();
        System.out.println("======================================================================================");
        RazerBlade razerBlade=new RazerBlade();
        razerBlade.features();
        System.out.println("======================================================================================");
        ROG rog=new ROG();
        rog.features();
        System.out.println("======================================================================================");
        Samsung samsung=new Samsung();
        samsung.features();
        System.out.println("======================================================================================");
        Sony sony=new Sony();
        sony.features();
        System.out.println("======================================================================================");
        Toshiba toshiba=new Toshiba();
        toshiba.features();
    }

}
